<?php

$page_title = "Rick and Morty Episode Guide";
$nav_curr = "Season Guide";

function getPageContent() {
    echo '<ul>
                <li>
                    <img class="season-img" src="https://upload.wikimedia.org/wikipedia/en/b/b8/Rick_and_Morty_season_1.png" alt="Season 1 cover">
                    <br>
                    <br>
                    <div class="season-text">
                        <p> The first season of the American animated television series, Rick and Morty originally aired in the United States on Cartoon Network\'s late night programming block, Adult Swim. It premiered on December 2, 2013 with "Pilot" and ended on April 14, 2014 with "Ricksy Business", with a total of eleven episodes. The first season received critical acclaim.When the show first started back in December, it came off as a fun, twisted play on Doc Brown and Marty McFly\'s relationship from Back to the Future. And for a few episodes after the pilot, it was clear that spoofing famous sci-fi movies (Jurassic Park, Fantastic Voyage, Inception, etc) would be part of the show\'s DNA. Not the absolute height of creativity, but Rick and Morty still managed to do very funny, original things while riffing on cinema classics.Then we were hit with the trio of "Meeseeks and Destroy," "Rick Potion #9" (where Rick and Morty destroy and mutate all of Earth, forcing them to find a new reality), and "Raising Gazorpazorp" (where Morty impregnates a f***-bot) and it was clear that this show could take us to new, deranged levels of hilarity and uncomfortable weirdness. Like the best, mind-bending episodes of Futurama, but with more of a focus on the disturbing and perverse.

                            Then came "Rixty Minutes," the episode which, in a somewhat hipster-y publicity move, got released early via a series of 15 second clips on Instagram. Because Rick and Morty fans, apparently, were of the ilk that would be "up to the challenge." Whatever. Stunts are stunts. And it got Rick and Morty in the news that weekend. But I\'d more readily think that Rick and Morty fans wouldn\'t dare sacrifice the actual comedy of the show to watch it on a wonky medium. I checked out a few clips and - yup - it killed the laughs.

                            The actual episode however, when viewed normally, shined a spotlight on the fact that Rick and Morty could also take an extremely goofy time-out from its usual apocalyptic themes while the family sat and watched TV shows (thanks to one of Rick\'s devices) from every conceivable reality. And many an "obviously improvised in the recording studio" show was screened. Including a series from a world where hamsters live in people\'s butts and a version of Who\'s The Boss? from a world where all nouns start with "Shmluh" ("Shmlangela!" Shmlonathan!") Oh, and extra points awarded to Rick and Morty\'s casual conversation about the intertwining voice-over careers of Bill Murray and Lorenzo Music.I\'ll stick with "Rixty Minutes" a bit longer here in order to mention Morty\'s parents, Jerry and Beth (Chris Parnell and Sarah Chalke). It would be an easy move for a show to use the surrounding family unit as peripheral players, only bringing them in when a scolding or a "WTF?" reaction was in order. But Rick and Morty utilized all the family members wonderfully - especially weak-willed, delusional Jerry and his nutso narcissism. And most episodes, if things didn\'t end with the destruction of the universe, they closed out with Jerry and Beth either on the verge of divorce, wallowing in the acceptance of their own depression, or a discovering newfound lust for one another (usually brought about by the destruction of the universe).

                            The show also dabbled in pools of "meta" now and again. Like how Rick occasionally spoke to the audience and the conscious creation of his catch phrase ("Wubba Lubba Dub Dub!"). And even though it certainly felt like the reset button had been pushed at the top of most episodes, we found out in some of the later chapters that huge plot points actually did carry over. And it\'s here that we find the sort of humor and storytelling that we love on NBC\'s Community. In the season finale - "Ricksy Business" - we learned that all the chaos and death that happened in "Rick Potion #9" really happened. And that, indeed, Morty\'s corpse (from this newly hijacked reality) was still buried in the backyard. And that Rick\'s "Wubba Lubba" mantra was actual a signal that he was morbidly depressed and lonely. Amazing.As touching moments go, Rick and Morty used them sparingly. Bringing them out a bit more blatantly in the final two episodes of the season, where Rick bonded with Morty in "Close Rick-Counters of the Rick Kind" (despite having used him for years as a sort of "stupid brain waive" cloaking device), and then with both of his grandkids in "Ricksy Business" (teen Summer being the other, voiced by Spencer Grammar). Summer and Rick also got to have their own adventures together in "Raising Gazorpazorp" and "Something Ricked This Way Comes."
                        </p>
                    </div>
                    <br>
                    <br>
                </li>
                <li> 
                    <img class="season-img" src="https://upload.wikimedia.org/wikipedia/en/b/b1/Rick_and_Morty_season_2.png" alt="Season 2 cover">
                    <br>
                    <br>
                    <div class="season-text">
                        <p>
                            One of the more interesting wrinkles with this season was the increased focus on continuity between episodes. While each new installment is still largely standalone, the characters have become more prone to referencing past adventures. The show even built up a supporting cast of sorts, particularly when it came to the recurring appearances of Birdperson and Tammy. The show never got too hung up on continuity. Rather, creators Justin Roiland and Dan Harmon seemed to know just how hard to lean on it as a storytelling device so that some developments (particularly in the finale) carried more weight.

                            This emphasis on continuity was especially evident in the premiere episode, "Total Rickall," which served as a direct continuation of the Season 1 finale "Ricksy Business." Rick\'s decision to abuse of time travel to clean up the mess from his house party wound up splitting the timestream into four pieces, each of which unfolded simultaneously on screen. It was a clever concept that was executed with plenty of intelligence and humor. And that pretty much set the tone for the entire season. Many episodes hinged on high-concept storytelling mixed with plenty of hilarity and a dash of poignant character moments. Whether it was Rick hanging out with his ex-girlfriend (a collective consciousness occupying an entire planet\'s worth of people) in "Auto-Erotic Assimilation"  or the incredibly bizarre locked room mystery that was "Total Rickall," there was rarely a dull moment the entire season.

                            This season built pretty significantly on the previous season\'s revelations about Rick being a profoundly unhappy man. Rick had some real emotional low points over the course of these episodes, including showing a bout of suicidal behavior in "Auto-Erotic Assimilation" and retreating into a teenager\'s body in "Big Trouble in Little Sanchez." But our drunken hero also showed signs of positive growth this year, showing genuine love and affection for his family from time to time and even sacrificing his freedom to save them in the finale.

                            One area this season improved was in allowing all the members of the Smith family to shine. Morty himself became a slightly more assertive character, showing that he is growing and evolving thanks to his misadventures with Grandpa Rick. His evolution was key in "Look Who\'s Purging Now," where all his pent-up rage and sexual frustration exploded onto the screen in a violent orgy of destruction. In his own way, Morty is as emotionally disturbed as his grandfather, which makes those rare moments when Rick protect\'s Morty\'s innocence that much more endearing.

                            Meanwhile, Summer essentially became the unofficial third member of their group in the aftermath of "Total Rickall," which was a nice change from her being the show\'s stereotypical surly teenage girl. Even Beth and Jerry were put to better use. While some episodes still played them as the straight-laced, boring counterpoints to Rick, Morty and Summer, others allowed them to join in on the craziness. "Big Trouble in Little Sanchez" was great about taking their familiar marriage woes and using them as a springboard for something bigger and crazier.

                            There were some weeks where it seemed Rick and Morty was its own worst enemy. In a series that prides itself on high-concept storytelling, any case where the show is slightly less innovative or where it repeats old storylines is bound to stick out. "Get Schwifty" was one example of this problem. That episode hinged on an "intergalactic American Idol" concept that never quite gelled or lived up to the show\'s usual standard.

                            There was also "Interdimensional Cable 2: Tempting Fate," the one case where the increased emphasis on continuity might have done the show a disservice. This episode was a direct sequel to Season 1\'s classic "Rixty Minutes," repeating the concept of Rick modifying a TV set to pick up broadcasts from across the multiverse. No matter how many times the characters acknowledged the fact that they were rehashing an old storyline, it didn\'t help that episode feel as fresh or funny as the original.

                            But really, if episodes like "Get Schwifty" and "Interdimensional Cable 2" are the worst Rick and Morty has to offer, that speaks a lot for the show\'s overall quality. It\'s rare to see an animated sitcom of such wit and intelligence, and Roiland and Harmon can be forgiven if not every installment is a home run.
                        </p>
                    </div>
                </li>
                <li>
                    <img class="season-img" src="https://upload.wikimedia.org/wikipedia/en/5/52/Rick_and_Morty_season_3.png" alt="Season 3 cover">
                    <br>
                    <br>
                    <div class="season-text">
                        <p>
                            The first episode of Rick and Morty\'s third season ends with Rick breaking the fourth wall (as he\'s often wont to do) and telling his grandson that they\'re in store for the darkest, craziest season of their adventures yet. That scene really set the stage for what was to come. Season 3 lived up to its promising by even more dark and unpredictable than the previous two. It might be a stretch to call Season 3 the show\'s best, but in many ways it\'s the most consistent and ambitious so far.

                            That sense of unpredictability was in full effect right off the bat, as Adult Swim wound up airing the premiere, "The Rickshank Redemption," in a repeating block on April Fool\'s Day with no advance warning. Hey, at least that holiday finally became good for something. And given how long the wait between Seasons 2 and 3 was, it was a nice way to reward fans for their patience.As mentioned, "The Rickshank Redemption" very much set the tone for the season as a whole. The series was coming off one of best and most emotionally charged episodes in "The Wedding Squanchers." That episode ended on a hugely depressing note, with Rick making the ultimate sacrifice for his family, turning himself into the Federation to spare the rest of the Smith clan from a lifetime of exile on an undersized, empty world. "The Rickshank Redemption" managed to be depressing in a completely different way. Far from establishing that Rick had finally learned to put the needs of his family over his own selfish desires, the premiere saw Rick become even more unhinged and double-down on his arrogant, self-destructive behavior.

                            Thus, the stage was set for a very different status quo in Season 3. With Jerry mostly out of the picture and Beth ever more eager to please her perpetually absentee father, Rick\'s id lost whatever fragile safeguards were keeping it in check. What we saw over the course of the next nine episodes was Rick\'s dark side coming to the forefront. Literally, in the case of "Rest and Ricklaxation." From transforming himself into a talking pickle to waging all-out war on the President of the United States, Rick was never shy about seizing on whatever crazy scheme came to mind.

                            Rick\'s wacky behavior was the source of a steady stream of wacky, high-concept sci-fi storytelling. This series is nothing if not extremely clever, but there\'s always a fear that creators Justin Roiland and Dan Harmon will run out of ways to top themselves and keep pushing the envelope. Maybe the tank will run out of gas someday, but clearly not yet. For the most part, Season 3 was very good about avoiding episodes that rely too heavily on parodying other franchises ("Rickmancing the Stone" being the one major exception) or repeating plots from previous seasons. Thankfully, Roiland and Harmon avoided doing "Interdimensional Cable III," instead opting for the vignette-driven "The Ricklantis Mixup" and the faux-clip show "Morty\'s Mind Blowers." Nothing could top "Pickle Rick" for sheer hilarity and novelty factor, however.Apart from the high-concept storytelling,  Season 3 really excelled when it came to character development. While Rick and Morty has never been an especially continuity-driven sitcom, there\'s always a clearer sense of progression from the start of a season to the finale. That was especially true this year, with every main character beginning the season in a profoundly different place. Rick was more dominant and self-serving than ever, Beth was just beginning to discover her independence again, while Jerry had to grapple with the loss of his family and whatever shred of self-respect he might have had. And with the adults trapped in their own downward spirals, it fell on Morty and Summer to be the grown-ups in the family.

                            Morty in particular showed a tangible growth this season. No longer the nervous, constantly agitated sidekick to Rick, Morty began to assert himself and become the voice of reason in the face of his grandfather\'s over-the-top behavior. Even Roiland\'s Morty performance seemed a little different this year - reflecting a teenager making his way through puberty and slowly beginning to come to terms with himself. No episode did more to highlight and explore the Rick/Morty dynamic than "The Ricklantis Mixup," which downplayed the main duo in favor of their alternate universe counterparts at the Citadel. That episode offered a lot of fun insight into how the Rick/Morty partnership turned out in other universes, as well as set the stage for what should be an interesting conflict in Season 4.

                            It\'s easy to see why some fans might be underwhelmed with the way Season 3 ended.  "The Rickchurian Mortydate" didn\'t reach the dramatic or emotional heights of "The Wedding Squanchers." It was a fairly low-key wrap-up to the season. Still, it managed to bring closure to a season marked by wacky concepts and dark character drama. The finale saw several characters make key decisions about the course of their lives. And it forced Rick to finally account for and face consequences for his actions over the previous nine episodes. There\'s a certain misguided subsection of the Rick and Morty fanbase who view Rick as a role model and not a profoundly selfish man who usually becomes the architect of his own misfortunes. "The Rickchurian Mortydate" served as a necessary reminder than even Rick Sanchez can (and must) be defeated now and then.

                            Season 3 was a wild ride from start top finish. Unfortunately, it wasn\'t without a handful of flaws. The biggest being the relative lack of Jerry this year. Jerry is such a wonderfully entertaining and pathetic character that the series misses out whenever he stays out of the picture for too long. Less glaring but still annoying was the complete absence of Birdperson following his brief cameo in the premiere. There were also a couple episodes that didn\'t quite deliver on their potential. Like I mentioned before, "Rickmancing the Stone" never quite rose above its influences, which made it feel more on par with early Season 1 Rick and Morty. And while "Morty\'s Mind Blowers" was a welcome shift away from the "Interdimensional Cable" formula, it didn\'t quite connect in the way "Rixty Minutes" did.

                            Still, despite these flaws, Season 3 is easily the most consistently good year of Rick and Morty yet. If it didn\'t quite reach the heights of Season 2\'s best episodes like "The Wedding Squanchers" and "Total Rickall" (an episode whose genius I\'ll admit I didn\'t fully appreciate at the time), its mistakes were few and far between. As frustrating as the wait between seasons can be, as long as Roiland and Harmon keep delivering on this level, they can take all the time they need.
                        </p>
                    </div>
                    <br>
                    <br>
                </li>
            </ul>';
}

include('resources/template.php');

?>
